In [1]:
import selenium
import pandas as pd
from selenium import webdriver
import warnings
warnings.filterwarnings('ignore')
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException
from selenium.webdriver.common.by import By
import time

In [2]:
driver=webdriver.Chrome(r"/Users/naman/Downloads/chromedriver-mac-arm64/chromedriver")

In [3]:
driver.get("https://www.imdb.com/search/title/?genres=action&sort=user_rating,desc&title_type=feature&num_votes=25000,&pf_rd_m=A2FGELUUNOQJNL&pf_rd_p=f11158cc-b50b-4c4d-b0a2-40b32863395b&pf_rd_r=XZ8X52H1R40B7KG5SNZ9&pf_rd_s=right-6&pf_rd_t=15506&pf_rd_i=top&ref_=chttp_gnr_1")

In [4]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [5]:
page = requests.get("https://www.imdb.com/search/title/?genres=action&sort=user_rating,desc&title_type=feature&num_votes=25000,&pf_rd_m=A2FGELUUNOQJNL&pf_rd_p=f11158cc-b50b-4c4d-b0a2-40b32863395b&pf_rd_r=XZ8X52H1R40B7KG5SNZ9&pf_rd_s=right-6&pf_rd_t=15506&pf_rd_i=top&ref_=chttp_gnr_1")

In [6]:
page

In [7]:
url = "https://www.imdb.com/search/title/?genres=action&sort=user_rating,desc&title_type=feature&num_votes=25000,&pf_rd_m=A2FGELUUNOQJNL&pf_rd_p=f11158cc-b50b-4c4d-b0a2-40b32863395b&pf_rd_r=XZ8X52H1R40B7KG5SNZ9&pf_rd_s=right-6&pf_rd_t=15506&pf_rd_i=top&ref_=chttp_gnr_1"
response = requests.get(url)

In [8]:
soup = BeautifulSoup(response.content, "html.parser")

# Sno

In [9]:
Sno = []

for i in soup.find_all('span', class_='lister-item-index unbold text-primary'):
    Sno.append(i.text)
    
Sno

['1.',
 '2.',
 '3.',
 '4.',
 '5.',
 '6.',
 '7.',
 '8.',
 '9.',
 '10.',
 '11.',
 '12.',
 '13.',
 '14.',
 '15.',
 '16.',
 '17.',
 '18.',
 '19.',
 '20.',
 '21.',
 '22.',
 '23.',
 '24.',
 '25.',
 '26.',
 '27.',
 '28.',
 '29.',
 '30.',
 '31.',
 '32.',
 '33.',
 '34.',
 '35.',
 '36.',
 '37.',
 '38.',
 '39.',
 '40.',
 '41.',
 '42.',
 '43.',
 '44.',
 '45.',
 '46.',
 '47.',
 '48.',
 '49.',
 '50.']

In [10]:
len(Sno)

50

# Movie Name

In [11]:
name = soup.find_all("h3", class_="lister-item-header")

movies_name = []
for i in name:
    for j in i.find_all("a"):
        movies_name.append(j.text)

In [12]:
movies_name

['The Dark Knight',
 'The Lord of the Rings: The Return of the King',
 'Spider-Man: Across the Spider-Verse',
 'Inception',
 'The Lord of the Rings: The Fellowship of the Ring',
 'The Lord of the Rings: The Two Towers',
 'The Matrix',
 'Star Wars: Episode V - The Empire Strikes Back',
 'Soorarai Pottru',
 'Terminator 2: Judgment Day',
 'Star Wars',
 'Shichinin no samurai',
 'Seppuku',
 'Sita Ramam',
 'Gladiator',
 'Léon',
 'The Dark Knight Rises',
 'Avengers: Endgame',
 'Spider-Man: Into the Spider-Verse',
 'Raiders of the Lost Ark',
 'Aliens',
 'Oldeuboi',
 'Avengers: Infinity War',
 'Kaithi',
 'Asuran',
 'Top Gun: Maverick',
 'Heat',
 'North by Northwest',
 'Star Wars: Episode VI - Return of the Jedi',
 'Mononoke-hime',
 'Dangal',
 'Kantara',
 'Vikram',
 'K.G.F: Chapter 2',
 'Shershaah',
 'Ratsasan',
 'Batman Begins',
 'Spider-Man: No Way Home',
 'Jurassic Park',
 '1917',
 'Indiana Jones and the Last Crusade',
 'Kill Bill: Vol. 1',
 'V for Vendetta',
 'Die Hard',
 'Ran',
 'Kimetsu no Yaiba: Mugen Ressha-Hen',
 'Gangs of Wasseypur',
 'Yôjinbô',
 'K.G.F: Chapter 1',
 'Baahubali 2: The Conclusion']

In [13]:
len(movies_name)

50

# Directors

In [14]:
director = soup.find_all("p", class_ = '')
director11 = []
stars=[]

finaldirector = []
row=[]

director1=[]
director2=[]
director3=[]

for i in director:
    c=1
    row.clear()
    for j in i.find_all():
        
        if(j.name=="span"):
            break
        else:
            director11.append(j.text)
            row.append(j.text)
    
    if len(row)==1:
        director1.append(row[0])
        director2.append("NaN")
        director3.append("NaN")
    elif len(row)==2:
        director1.append(row[0])
        director2.append(row[1])
        director3.append("NaN")
    else:
        director1.append(row[0])
        director2.append(row[1])
        director3.append(row[2])
        
director1

['Christopher Nolan',
 'Peter Jackson',
 'Joaquim Dos Santos',
 'Christopher Nolan',
 'Peter Jackson',
 'Peter Jackson',
 'Lana Wachowski',
 'Irvin Kershner',
 'Sudha Kongara',
 'James Cameron',
 'George Lucas',
 'Akira Kurosawa',
 'Masaki Kobayashi',
 'Hanu Raghavapudi',
 'Ridley Scott',
 'Luc Besson',
 'Christopher Nolan',
 'Anthony Russo',
 'Bob Persichetti',
 'Steven Spielberg',
 'James Cameron',
 'Park Chan-wook',
 'Anthony Russo',
 'Lokesh Kanagaraj',
 'Vetrimaaran',
 'Joseph Kosinski',
 'Michael Mann',
 'Alfred Hitchcock',
 'Richard Marquand',
 'Hayao Miyazaki',
 'Nitesh Tiwari',
 'Rishab Shetty',
 'Lokesh Kanagaraj',
 'Prashanth Neel',
 'Vishnuvardhan',
 'Ram Kumar',
 'Christopher Nolan',
 'Jon Watts',
 'Steven Spielberg',
 'Sam Mendes',
 'Steven Spielberg',
 'Quentin Tarantino',
 'James McTeigue',
 'John McTiernan',
 'Akira Kurosawa',
 'Haruo Sotozaki',
 'Anurag Kashyap',
 'Akira Kurosawa',
 'Prashanth Neel',
 'S.S. Rajamouli']

In [15]:
len(director1)

50

In [16]:
director2

['NaN',
 'NaN',
 'Kemp Powers',
 'NaN',
 'NaN',
 'NaN',
 'Lilly Wachowski',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'Joe Russo',
 'Peter Ramsey',
 'NaN',
 'NaN',
 'NaN',
 'Joe Russo',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN']

In [17]:
len(director2)

50

In [18]:
director3

['NaN',
 'NaN',
 'Justin K. Thompson',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'Rodney Rothman',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN']

In [19]:
len(director3)

50

# Duration

In [20]:
duration = soup.find_all("p", class_="text-muted")

Duration = []
for i in duration:
    for j in i.find_all("span", class_="runtime"):
        Duration.append(j.text)

In [21]:
Duration

['152 min',
 '201 min',
 '140 min',
 '148 min',
 '178 min',
 '179 min',
 '136 min',
 '124 min',
 '153 min',
 '137 min',
 '121 min',
 '207 min',
 '133 min',
 '163 min',
 '155 min',
 '110 min',
 '164 min',
 '181 min',
 '117 min',
 '115 min',
 '137 min',
 '101 min',
 '149 min',
 '145 min',
 '141 min',
 '130 min',
 '170 min',
 '136 min',
 '131 min',
 '134 min',
 '161 min',
 '148 min',
 '175 min',
 '168 min',
 '135 min',
 '170 min',
 '140 min',
 '148 min',
 '127 min',
 '119 min',
 '127 min',
 '111 min',
 '132 min',
 '132 min',
 '162 min',
 '117 min',
 '321 min',
 '110 min',
 '156 min',
 '167 min']

In [22]:
len(Duration)

50

# Year

In [23]:
year = soup.find_all("h3", class_="lister-item-header")

Year = []
for i in year:
    for j in i.find_all("span", class_="lister-item-year text-muted unbold"):
        Year.append(j.text)

In [24]:
Year

['(2008)',
 '(2003)',
 '(2023)',
 '(2010)',
 '(2001)',
 '(2002)',
 '(1999)',
 '(1980)',
 '(2020)',
 '(1991)',
 '(1977)',
 '(1954)',
 '(1962)',
 '(2022)',
 '(2000)',
 '(1994)',
 '(2012)',
 '(2019)',
 '(2018)',
 '(1981)',
 '(1986)',
 '(2003)',
 '(2018)',
 '(2019)',
 '(2019)',
 '(2022)',
 '(1995)',
 '(1959)',
 '(1983)',
 '(1997)',
 '(2016)',
 '(2022)',
 '(2022)',
 '(2022)',
 '(2021)',
 '(2018)',
 '(2005)',
 '(2021)',
 '(1993)',
 '(2019)',
 '(1989)',
 '(2003)',
 '(2005)',
 '(1988)',
 '(1985)',
 '(2020)',
 '(2012)',
 '(1961)',
 '(2018)',
 '(2017)']

In [25]:
len(Year)

50

# Rating

In [26]:
rating = soup.find_all("div", class_="inline-block ratings-imdb-rating")

Rating = []
for i in rating:
    for j in i.find_all("strong"):
        Rating.append(j.text)

In [27]:
Rating

['9.0',
 '9.0',
 '8.9',
 '8.8',
 '8.8',
 '8.8',
 '8.7',
 '8.7',
 '8.7',
 '8.6',
 '8.6',
 '8.6',
 '8.6',
 '8.6',
 '8.5',
 '8.5',
 '8.4',
 '8.4',
 '8.4',
 '8.4',
 '8.4',
 '8.4',
 '8.4',
 '8.4',
 '8.4',
 '8.3',
 '8.3',
 '8.3',
 '8.3',
 '8.3',
 '8.3',
 '8.3',
 '8.3',
 '8.3',
 '8.3',
 '8.3',
 '8.2',
 '8.2',
 '8.2',
 '8.2',
 '8.2',
 '8.2',
 '8.2',
 '8.2',
 '8.2',
 '8.2',
 '8.2',
 '8.2',
 '8.2',
 '8.2']

In [28]:
len(Rating)

50

# Metascore

In [29]:
ratingbar = soup.find_all("div", class_="ratings-bar")

Metascore = []
for i in ratingbar:
    if i.find("div", class_="inline-block ratings-metascore"):
        for j in i.find_all("div", class_="inline-block ratings-metascore"):
            Metascore.append(j.text.split(" ")[0].split("\n")[1])
    else:
        Metascore.append("NaN")
        
Metascore

['84',
 '94',
 '86',
 '74',
 '92',
 '87',
 '73',
 '82',
 'NaN',
 '75',
 '90',
 '98',
 '85',
 'NaN',
 '67',
 '64',
 '78',
 '78',
 '87',
 '85',
 '84',
 '77',
 '68',
 'NaN',
 'NaN',
 '78',
 '76',
 '98',
 '58',
 '76',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 'NaN',
 '70',
 '71',
 '68',
 '78',
 '65',
 '69',
 '62',
 '72',
 '97',
 '72',
 '89',
 '93',
 'NaN',
 'NaN']

In [30]:
len(Metascore)

50

# Dataframe1

In [31]:
print(len(Sno),len(movies_name),len(director1),len(director2),len(director3),len(Duration),len(Year),len(Rating),len(Metascore))

50 50 50 50 50 50 50 50 50

In [32]:
df1=pd.DataFrame({'Sno':Sno,'Movie Name':movies_name,'Director1':director1,'Director2':director2,'Director3':director3,'Duration':Duration,'Year':Year,'Rating':Rating,'Metascore':Metascore})

In [33]:
df1

,Sno,Movie Name,Director1,Director2,Director3,Duration,Year,Rating,Metascore
0,1.,The Dark Knight,Christopher Nolan,NaN,NaN,152 min,(2008),9.0,84
1,2.,The Lord of the Rings: The Return of the King,Peter Jackson,NaN,NaN,201 min,(2003),9.0,94
2,3.,Spider-Man: Across the Spider-Verse,Joaquim Dos Santos,Kemp Powers,Justin K. Thompson,140 min,(2023),8.9,86
3,4.,Inception,Christopher Nolan,NaN,NaN,148 min,(2010),8.8,74
4,5.,The Lord of the Rings: The Fellowship of the Ring,Peter Jackson,NaN,NaN,178 min,(2001),8.8,92
5,6.,The Lord of the Rings: The Two Towers,Peter Jackson,NaN,NaN,179 min,(2002),8.8,87
6,7.,The Matrix,Lana Wachowski,Lilly Wachowski,NaN,136 min,(1999),8.7,73
7,8.,Star Wars: Episode V - The Empire Strikes Back,Irvin Kershner,NaN,NaN,124 min,(1980),8.7,82
8,9.,Soorarai Pottru,Sudha Kongara,NaN,NaN,153 min,(2020),8.7,NaN
9,10.,Terminator 2: Judgment Day,James Cameron,NaN,NaN,137 min,(1991),8.6,75
10,11.,Star Wars,George Lucas,NaN,NaN,121 min,(1977),8.6,90
11,12.,Shichinin no samurai,Akira Kurosawa,NaN,NaN,207 min,(1954),8.6,98
12,13.,Seppuku,Masaki Kobayashi,NaN,NaN,133 min,(1962),8.6,85
13,14.,Sita Ramam,Hanu Raghavapudi,NaN,NaN,163 min,(2022),8.6,NaN
14,15.,Gladiator,Ridley Scott,NaN,NaN,155 min,(2000),8.5,67
15,16.,Léon,Luc Besson,NaN,NaN,110 min,(1994),8.5,64
16,17.,The Dark Knight Rises,Christopher Nolan,NaN,NaN,164 min,(2012),8.4,78
17,18.,Avengers: Endgame,Anthony Russo,Joe Russo,NaN,181 min,(2019),8.4,78
18,19.,Spider-Man: Into the Spider-Verse,Bob Persichetti,Peter Ramsey,Rodney Rothman,117 min,(2018),8.4,87
19,20.,Raiders of the Lost Ark,Steven Spielberg,NaN,NaN,115 min,(1981),8.4,85
20,21.,Aliens,James Cameron,NaN,NaN,137 min,(1986),8.4,84
21,22.,Oldeuboi,Park Chan-wook,NaN,NaN,101 min,(2003),8.4,77
22,23.,Avengers: Infinity War,Anthony Russo,Joe Russo,NaN,149 min,(2018),8.4,68
23,24.,Kaithi,Lokesh Kanagaraj,NaN,NaN,145 min,(2019),8.4,NaN
24,25.,Asuran,Vetrimaaran,NaN,NaN,141 min,(2019),8.4,NaN
25,26.,Top Gun: Maverick,Joseph Kosinski,NaN,NaN,130 min,(2022),8.3,78
26,27.,Heat,Michael Mann,NaN,NaN,170 min,(1995),8.3,76
27,28.,North by Northwest,Alfred Hitchcock,NaN,NaN,136 min,(1959),8.3,98
28,29.,Star Wars: Episode VI - Return of the Jedi,Richard Marquand,NaN,NaN,131 min,(1983),8.3,58
29,30.,Mononoke-hime,Hayao Miyazaki,NaN,NaN,134 min,(1997),8.3,76
30,31.,Dangal,Nitesh Tiwari,NaN,NaN,161 min,(2016),8.3,NaN
31,32.,Kantara,Rishab Shetty,NaN,NaN,148 min,(2022),8.3,NaN
32,33.,Vikram,Lokesh Kanagaraj,NaN,NaN,175 min,(2022),8.3,NaN
33,34.,K.G.F: Chapter 2,Prashanth Neel,NaN,NaN,168 min,(2022),8.3,NaN
34,35.,Shershaah,Vishnuvardhan,NaN,NaN,135 min,(2021),8.3,NaN
35,36.,Ratsasan,Ram Kumar,NaN,NaN,170 min,(2018),8.3,NaN
36,37.,Batman Begins,Christopher Nolan,NaN,NaN,140 min,(2005),8.2,70
37,38.,Spider-Man: No Way Home,Jon Watts,NaN,NaN,148 min,(2021),8.2,71
38,39.,Jurassic Park,Steven Spielberg,NaN,NaN,127 min,(1993),8.2,68
39,40.,1917,Sam Mendes,NaN,NaN,119 min,(2019),8.2,78
40,41.,Indiana Jones and the Last Crusade,Steven Spielberg,NaN,NaN,127 min,(1989),8.2,65
41,42.,Kill Bill: Vol. 1,Quentin Tarantino,NaN,NaN,111 min,(2003),8.2,69
42,43.,V for Vendetta,James McTeigue,NaN,NaN,132 min,(2005),8.2,62
43,44.,Die Hard,John McTiernan,NaN,NaN,132 min,(1988),8.2,72
44,45.,Ran,Akira Kurosawa,NaN,NaN,162 min,(1985),8.2,97
45,46.,Kimetsu no Yaiba: Mugen Ressha-Hen,Haruo Sotozaki,NaN,NaN,117 min,(2020),8.2,72
46,47.,Gangs of Wasseypur,Anurag Kashyap,NaN,NaN,321 min,(2012),8.2,89
47,48.,Yôjinbô,Akira Kurosawa,NaN,NaN,110 min,(1961),8.2,93
48,49.,K.G.F: Chapter 1,Prashanth Neel,NaN,NaN,156 min,(2018),8.2,NaN
49,50.,Baahubali 2: The Conclusion,S.S. Rajamouli,NaN,NaN,167 min,(2017),8.2,NaN

In [34]:
df1.to_csv('first.csv')

# CSV2

# Movie name

In [35]:
name = soup.find_all("h3", class_="lister-item-header")

movies_name = []
for i in name:
    for j in i.find_all("a"):
        movies_name.append(j.text)
        
movies_name

['The Dark Knight',
 'The Lord of the Rings: The Return of the King',
 'Spider-Man: Across the Spider-Verse',
 'Inception',
 'The Lord of the Rings: The Fellowship of the Ring',
 'The Lord of the Rings: The Two Towers',
 'The Matrix',
 'Star Wars: Episode V - The Empire Strikes Back',
 'Soorarai Pottru',
 'Terminator 2: Judgment Day',
 'Star Wars',
 'Shichinin no samurai',
 'Seppuku',
 'Sita Ramam',
 'Gladiator',
 'Léon',
 'The Dark Knight Rises',
 'Avengers: Endgame',
 'Spider-Man: Into the Spider-Verse',
 'Raiders of the Lost Ark',
 'Aliens',
 'Oldeuboi',
 'Avengers: Infinity War',
 'Kaithi',
 'Asuran',
 'Top Gun: Maverick',
 'Heat',
 'North by Northwest',
 'Star Wars: Episode VI - Return of the Jedi',
 'Mononoke-hime',
 'Dangal',
 'Kantara',
 'Vikram',
 'K.G.F: Chapter 2',
 'Shershaah',
 'Ratsasan',
 'Batman Begins',
 'Spider-Man: No Way Home',
 'Jurassic Park',
 '1917',
 'Indiana Jones and the Last Crusade',
 'Kill Bill: Vol. 1',
 'V for Vendetta',
 'Die Hard',
 'Ran',
 'Kimetsu no Yaiba: Mugen Ressha-Hen',
 'Gangs of Wasseypur',
 'Yôjinbô',
 'K.G.F: Chapter 1',
 'Baahubali 2: The Conclusion']

In [36]:
len(movies_name)

50

# Stars

In [37]:
director = soup.find_all("p", class_ = '')
director1 = []
stars=[]

finaldirector = []
row=[]

star1=[]
star2=[]
star3=[]
star4=[]
for i in director:
    row.clear()
    for j in i.find_all():
        
        if(j.name=="span"):
            c=1
            for element in j.next_siblings:
                if element.name=='a':
                    if c==1:
                        star1.append(element.text)
                    elif c==2:
                        star2.append(element.text)
                    elif c==3:
                        star3.append(element.text)
                    elif c==4:
                        star4.append(element.text)
                    
                    c=c+1

In [38]:
star1

['Christian Bale',
 'Elijah Wood',
 'Shameik Moore',
 'Leonardo DiCaprio',
 'Elijah Wood',
 'Elijah Wood',
 'Keanu Reeves',
 'Mark Hamill',
 'Suriya',
 'Arnold Schwarzenegger',
 'Mark Hamill',
 'Toshirô Mifune',
 'Tatsuya Nakadai',
 'Dulquer Salmaan',
 'Russell Crowe',
 'Jean Reno',
 'Christian Bale',
 'Robert Downey Jr.',
 'Shameik Moore',
 'Harrison Ford',
 'Sigourney Weaver',
 'Choi Min-sik',
 'Robert Downey Jr.',
 'Karthi',
 'Dhanush',
 'Tom Cruise',
 'Al Pacino',
 'Cary Grant',
 'Mark Hamill',
 'Yôji Matsuda',
 'Aamir Khan',
 'Rishab Shetty',
 'Kamal Haasan',
 'Yash',
 'Sidharth Malhotra',
 'Vishnu Vishal',
 'Christian Bale',
 'Tom Holland',
 'Sam Neill',
 'Dean-Charles Chapman',
 'Harrison Ford',
 'Uma Thurman',
 'Hugo Weaving',
 'Bruce Willis',
 'Tatsuya Nakadai',
 'Natsuki Hanae',
 'Manoj Bajpayee',
 'Toshirô Mifune',
 'Yash',
 'Prabhas']

In [39]:
len(star1)

50

In [40]:
star2

['Heath Ledger',
 'Viggo Mortensen',
 'Hailee Steinfeld',
 'Joseph Gordon-Levitt',
 'Ian McKellen',
 'Ian McKellen',
 'Laurence Fishburne',
 'Harrison Ford',
 'Paresh Rawal',
 'Linda Hamilton',
 'Harrison Ford',
 'Takashi Shimura',
 'Akira Ishihama',
 'Mrunal Thakur',
 'Joaquin Phoenix',
 'Gary Oldman',
 'Tom Hardy',
 'Chris Evans',
 'Jake Johnson',
 'Karen Allen',
 'Michael Biehn',
 'Yoo Ji-tae',
 'Chris Hemsworth',
 'Narain',
 'Manju Warrier',
 'Jennifer Connelly',
 'Robert De Niro',
 'Eva Marie Saint',
 'Harrison Ford',
 'Yuriko Ishida',
 'Sakshi Tanwar',
 'Kishore Kumar G.',
 'Vijay Sethupathi',
 'Sanjay Dutt',
 'Kiara Advani',
 'Amala Paul',
 'Michael Caine',
 'Zendaya',
 'Laura Dern',
 'George MacKay',
 'Sean Connery',
 'David Carradine',
 'Natalie Portman',
 'Alan Rickman',
 'Akira Terao',
 'Akari Kitô',
 'Nawazuddin Siddiqui',
 'Eijirô Tôno',
 'Srinidhi Shetty',
 'Rana Daggubati']

In [41]:
len(star2)

50

In [42]:
star3

['Aaron Eckhart',
 'Ian McKellen',
 'Brian Tyree Henry',
 'Elliot Page',
 'Orlando Bloom',
 'Viggo Mortensen',
 'Carrie-Anne Moss',
 'Carrie Fisher',
 'Urvashi',
 'Edward Furlong',
 'Carrie Fisher',
 'Keiko Tsushima',
 'Shima Iwashita',
 'Rashmika Mandanna',
 'Connie Nielsen',
 'Natalie Portman',
 'Anne Hathaway',
 'Mark Ruffalo',
 'Hailee Steinfeld',
 'Paul Freeman',
 'Carrie Henn',
 'Kang Hye-jeong',
 'Mark Ruffalo',
 'Arjun Das',
 'Prakash Raj',
 'Miles Teller',
 'Val Kilmer',
 'James Mason',
 'Carrie Fisher',
 'Yûko Tanaka',
 'Fatima Sana Shaikh',
 'Achyuth Kumar',
 'Fahadh Faasil',
 'Raveena Tandon',
 'Shiv Panditt',
 'Radha Ravi',
 'Ken Watanabe',
 'Benedict Cumberbatch',
 'Jeff Goldblum',
 'Daniel Mays',
 'Alison Doody',
 'Daryl Hannah',
 'Rupert Graves',
 'Bonnie Bedelia',
 'Jinpachi Nezu',
 'Yoshitsugu Matsuoka',
 'Tigmanshu Dhulia',
 'Tatsuya Nakadai',
 'Ramachandra Raju',
 'Anushka Shetty']

In [43]:
len(star3)

50

In [44]:
star4

['Michael Caine',
 'Orlando Bloom',
 'Luna Lauren Velez',
 'Ken Watanabe',
 'Sean Bean',
 'Orlando Bloom',
 'Hugo Weaving',
 'Billy Dee Williams',
 'Aparna Balamurali',
 'Robert Patrick',
 'Alec Guinness',
 'Yukiko Shimazaki',
 'Tetsurô Tanba',
 'Sumanth',
 'Oliver Reed',
 'Danny Aiello',
 'Gary Oldman',
 'Chris Hemsworth',
 'Mahershala Ali',
 'John Rhys-Davies',
 'Paul Reiser',
 'Kim Byeong-Ok',
 'Chris Evans',
 'George Maryan',
 'Pasupathy',
 'Val Kilmer',
 'Jon Voight',
 'Jessie Royce Landis',
 'Billy Dee Williams',
 'Billy Crudup',
 'Sanya Malhotra',
 'Sapthami Gowda',
 'Narain',
 'Srinidhi Shetty',
 'Pranay Pachauri',
 'Sangili Murugan',
 'Liam Neeson',
 'Jacob Batalon',
 'Richard Attenborough',
 'Colin Firth',
 'Denholm Elliott',
 'Michael Madsen',
 'Stephen Rea',
 'Reginald VelJohnson',
 'Daisuke Ryû',
 'Hiro Shimono',
 'Richa Chadha',
 'Yôko Tsukasa',
 'Archana Jois',
 'Tamannaah Bhatia']

In [45]:
len(star4)

50

# Genre

In [46]:
genre = soup.find_all("p", class_="text-muted")
genre11=[]
row=[]

genre1=[]
genre2=[]
genre3=[]

for i in genre:
    c=1
    row.clear()
    for j in i.find_all("span", class_="genre"):
        genre11.append(j.text)
        row.append(j.text)
    #elements=row.split(',')
    for x in row:
        #print(x)
        
    
        if len(x.split(','))==1:
            genre1.append(x.split(',')[0].split('\n')[1])
            genre2.append("NaN")
            genre3.append("NaN")
        elif len(x.split(','))==2:
            genre1.append(x.split(',')[0].split('\n')[1])
            genre2.append((x.split(',')[1]).strip())
            genre3.append("NaN")
        else:
            genre1.append(x.split(',')[0].split('\n')[1])
            genre2.append((x.split(',')[1]).strip())
            genre3.append(x.split(',')[2].strip())
        
genre1

['Action',
 'Action',
 'Animation',
 'Action',
 'Action',
 'Action',
 'Action',
 'Action',
 'Action',
 'Action',
 'Action',
 'Action',
 'Action',
 'Action',
 'Action',
 'Action',
 'Action',
 'Action',
 'Animation',
 'Action',
 'Action',
 'Action',
 'Action',
 'Action',
 'Action',
 'Action',
 'Action',
 'Action',
 'Action',
 'Animation',
 'Action',
 'Action',
 'Action',
 'Action',
 'Action',
 'Action',
 'Action',
 'Action',
 'Action',
 'Action',
 'Action',
 'Action',
 'Action',
 'Action',
 'Action',
 'Animation',
 'Action',
 'Action',
 'Action',
 'Action']

In [47]:
len(genre1)

50

In [48]:
genre2

['Crime',
 'Adventure',
 'Action',
 'Adventure',
 'Adventure',
 'Adventure',
 'Sci-Fi',
 'Adventure',
 'Drama',
 'Sci-Fi',
 'Adventure',
 'Drama',
 'Drama',
 'Drama',
 'Adventure',
 'Crime',
 'Drama',
 'Adventure',
 'Action',
 'Adventure',
 'Adventure',
 'Drama',
 'Adventure',
 'Adventure',
 'Drama',
 'Drama',
 'Crime',
 'Adventure',
 'Adventure',
 'Action',
 'Biography',
 'Adventure',
 'Crime',
 'Crime',
 'Biography',
 'Crime',
 'Crime',
 'Adventure',
 'Adventure',
 'Drama',
 'Adventure',
 'Crime',
 'Drama',
 'Thriller',
 'Drama',
 'Action',
 'Comedy',
 'Drama',
 'Crime',
 'Drama']

In [49]:
len(genre2)

50

In [50]:
genre3

['Drama',
 'Drama',
 'Adventure',
 'Sci-Fi',
 'Drama',
 'Drama',
 'NaN',
 'Fantasy',
 'NaN',
 'NaN',
 'Fantasy',
 'NaN',
 'Mystery',
 'Mystery',
 'Drama',
 'Drama',
 'Thriller',
 'Drama',
 'Adventure',
 'NaN',
 'Sci-Fi',
 'Mystery',
 'Sci-Fi',
 'Crime',
 'NaN',
 'NaN',
 'Drama',
 'Mystery',
 'Fantasy',
 'Adventure',
 'Drama',
 'Drama',
 'Thriller',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Fantasy',
 'Sci-Fi',
 'War',
 'NaN',
 'Thriller',
 'Sci-Fi',
 'NaN',
 'War',
 'Adventure',
 'Crime',
 'Thriller',
 'Drama',
 'NaN']

In [51]:
len(genre3)

50

# Vote

In [52]:
gross = soup.find_all("p", class_="sort-num_votes-visible")

Gross = []
vote=[]

for i in gross:
    if(len(i.find_all("span", {'name':'nv'})) == 2):
        c=1
        for j in i.find_all("span", {'name':'nv'}):
            if(c==1):
                vote.append(j.text)
            else:
                Gross.append(j.text)
            c=c+1
            
    elif(len(i.find_all("span", {'name':'nv'})) == 1):
        
        for j in i.find_all("span", {'name':'nv'}):
        
                vote.append(j.text)
            
                Gross.append("NaN")
            
            
vote

['2,759,120',
 '1,906,310',
 '207,811',
 '2,449,440',
 '1,934,517',
 '1,720,205',
 '1,978,885',
 '1,334,714',
 '120,274',
 '1,135,381',
 '1,406,735',
 '356,128',
 '62,777',
 '61,885',
 '1,552,493',
 '1,202,203',
 '1,764,411',
 '1,203,309',
 '617,858',
 '1,007,837',
 '739,403',
 '604,480',
 '1,145,018',
 '37,005',
 '31,663',
 '619,582',
 '686,833',
 '337,316',
 '1,087,935',
 '412,506',
 '200,058',
 '97,289',
 '65,185',
 '141,534',
 '125,851',
 '47,666',
 '1,523,960',
 '821,175',
 '1,027,406',
 '634,995',
 '787,477',
 '1,152,058',
 '1,149,274',
 '908,755',
 '130,929',
 '66,779',
 '100,143',
 '127,195',
 '92,940',
 '108,482']

In [53]:
len(vote)

50

# Gross

In [54]:
Gross

['$534.86M',
 '$377.85M',
 'NaN',
 '$292.58M',
 '$315.54M',
 '$342.55M',
 '$171.48M',
 '$290.48M',
 'NaN',
 '$204.84M',
 '$322.74M',
 '$0.27M',
 'NaN',
 'NaN',
 '$187.71M',
 '$19.50M',
 '$448.14M',
 '$858.37M',
 '$190.24M',
 '$248.16M',
 '$85.16M',
 '$0.71M',
 '$678.82M',
 'NaN',
 'NaN',
 '$718.73M',
 '$67.44M',
 '$13.28M',
 '$309.13M',
 '$2.38M',
 '$12.39M',
 'NaN',
 'NaN',
 '$6.60M',
 'NaN',
 'NaN',
 '$206.85M',
 '$804.75M',
 '$402.45M',
 '$159.23M',
 '$197.17M',
 '$70.10M',
 '$70.51M',
 '$83.01M',
 '$4.14M',
 '$47.70M',
 'NaN',
 'NaN',
 'NaN',
 '$20.19M']

In [55]:
len(Gross)

50

# Popularity

In [56]:
popularity = soup.find_all("div", class_="inline-block ratings-imdb-rating")

Popularity = []
for i in popularity:
    for j in i.find_all("strong"):
        Popularity.append(j.text)
        
Popularity

['9.0',
 '9.0',
 '8.9',
 '8.8',
 '8.8',
 '8.8',
 '8.7',
 '8.7',
 '8.7',
 '8.6',
 '8.6',
 '8.6',
 '8.6',
 '8.6',
 '8.5',
 '8.5',
 '8.4',
 '8.4',
 '8.4',
 '8.4',
 '8.4',
 '8.4',
 '8.4',
 '8.4',
 '8.4',
 '8.3',
 '8.3',
 '8.3',
 '8.3',
 '8.3',
 '8.3',
 '8.3',
 '8.3',
 '8.3',
 '8.3',
 '8.3',
 '8.2',
 '8.2',
 '8.2',
 '8.2',
 '8.2',
 '8.2',
 '8.2',
 '8.2',
 '8.2',
 '8.2',
 '8.2',
 '8.2',
 '8.2',
 '8.2']

In [57]:
len(Popularity)

50

# Certificate

In [58]:
movie_certificate=[]

movie_certificate_tags=driver.find_elements(By.XPATH, '//span[@class="certificate"]')
for i in movie_certificate_tags[0:50]:
    certificate=i.text
    movie_certificate.append(certificate)
    
movie_certificate

['PG-13',
 'PG-13',
 'PG',
 'PG-13',
 'PG-13',
 'PG-13',
 'R',
 'PG',
 'TV-MA',
 'R',
 'PG',
 'Not Rated',
 'Not Rated',
 'U',
 'R',
 'R',
 'PG-13',
 'PG-13',
 'PG',
 'PG',
 'R',
 'R',
 'PG-13',
 'Not Rated',
 'Not Rated',
 'PG-13',
 'R',
 'Approved',
 'PG',
 'PG-13',
 'Not Rated',
 'Not Rated',
 'UA',
 'Not Rated',
 'TV-14',
 'Not Rated',
 'PG-13',
 'PG-13',
 'PG-13',
 'R',
 'PG-13',
 'R',
 'R',
 'R',
 'R',
 'R',
 'Not Rated',
 'Not Rated',
 'Not Rated',
 'Not Rated']

In [59]:
len(movie_certificate)

50

In [60]:
print(len(movies_name),len(star1),len(star2),len(star3),len(star4),len(vote),len(genre1),len(genre2),len(genre3),len(Gross),len(Popularity), len(movie_certificate))

50 50 50 50 50 50 50 50 50 50 50 50

In [61]:
df2=pd.DataFrame({'Movie Name':movies_name,'Star1':star1,'Star2':star2,'Star3':star3,'Star4':star4,'Votes':vote,'Genre1':genre1,'Genre2':genre2,'Genre3':genre3,'Gross collection':Gross, 'Popularity':Popularity, 'Certification':movie_certificate})

In [62]:
df2

,Movie Name,Star1,Star2,Star3,Star4,Votes,Genre1,Genre2,Genre3,Gross collection,Popularity,Certification
0,The Dark Knight,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,"2,759,120",Action,Crime,Drama,$534.86M,9.0,PG-13
1,The Lord of the Rings: The Return of the King,Elijah Wood,Viggo Mortensen,Ian McKellen,Orlando Bloom,"1,906,310",Action,Adventure,Drama,$377.85M,9.0,PG-13
2,Spider-Man: Across the Spider-Verse,Shameik Moore,Hailee Steinfeld,Brian Tyree Henry,Luna Lauren Velez,"207,811",Animation,Action,Adventure,NaN,8.9,PG
3,Inception,Leonardo DiCaprio,Joseph Gordon-Levitt,Elliot Page,Ken Watanabe,"2,449,440",Action,Adventure,Sci-Fi,$292.58M,8.8,PG-13
4,The Lord of the Rings: The Fellowship of the Ring,Elijah Wood,Ian McKellen,Orlando Bloom,Sean Bean,"1,934,517",Action,Adventure,Drama,$315.54M,8.8,PG-13
5,The Lord of the Rings: The Two Towers,Elijah Wood,Ian McKellen,Viggo Mortensen,Orlando Bloom,"1,720,205",Action,Adventure,Drama,$342.55M,8.8,PG-13
6,The Matrix,Keanu Reeves,Laurence Fishburne,Carrie-Anne Moss,Hugo Weaving,"1,978,885",Action,Sci-Fi,NaN,$171.48M,8.7,R
7,Star Wars: Episode V - The Empire Strikes Back,Mark Hamill,Harrison Ford,Carrie Fisher,Billy Dee Williams,"1,334,714",Action,Adventure,Fantasy,$290.48M,8.7,PG
8,Soorarai Pottru,Suriya,Paresh Rawal,Urvashi,Aparna Balamurali,"120,274",Action,Drama,NaN,NaN,8.7,TV-MA
9,Terminator 2: Judgment Day,Arnold Schwarzenegger,Linda Hamilton,Edward Furlong,Robert Patrick,"1,135,381",Action,Sci-Fi,NaN,$204.84M,8.6,R
10,Star Wars,Mark Hamill,Harrison Ford,Carrie Fisher,Alec Guinness,"1,406,735",Action,Adventure,Fantasy,$322.74M,8.6,PG
11,Shichinin no samurai,Toshirô Mifune,Takashi Shimura,Keiko Tsushima,Yukiko Shimazaki,"356,128",Action,Drama,NaN,$0.27M,8.6,Not Rated
12,Seppuku,Tatsuya Nakadai,Akira Ishihama,Shima Iwashita,Tetsurô Tanba,"62,777",Action,Drama,Mystery,NaN,8.6,Not Rated
13,Sita Ramam,Dulquer Salmaan,Mrunal Thakur,Rashmika Mandanna,Sumanth,"61,885",Action,Drama,Mystery,NaN,8.6,U
14,Gladiator,Russell Crowe,Joaquin Phoenix,Connie Nielsen,Oliver Reed,"1,552,493",Action,Adventure,Drama,$187.71M,8.5,R
15,Léon,Jean Reno,Gary Oldman,Natalie Portman,Danny Aiello,"1,202,203",Action,Crime,Drama,$19.50M,8.5,R
16,The Dark Knight Rises,Christian Bale,Tom Hardy,Anne Hathaway,Gary Oldman,"1,764,411",Action,Drama,Thriller,$448.14M,8.4,PG-13
17,Avengers: Endgame,Robert Downey Jr.,Chris Evans,Mark Ruffalo,Chris Hemsworth,"1,203,309",Action,Adventure,Drama,$858.37M,8.4,PG-13
18,Spider-Man: Into the Spider-Verse,Shameik Moore,Jake Johnson,Hailee Steinfeld,Mahershala Ali,"617,858",Animation,Action,Adventure,$190.24M,8.4,PG
19,Raiders of the Lost Ark,Harrison Ford,Karen Allen,Paul Freeman,John Rhys-Davies,"1,007,837",Action,Adventure,NaN,$248.16M,8.4,PG
20,Aliens,Sigourney Weaver,Michael Biehn,Carrie Henn,Paul Reiser,"739,403",Action,Adventure,Sci-Fi,$85.16M,8.4,R
21,Oldeuboi,Choi Min-sik,Yoo Ji-tae,Kang Hye-jeong,Kim Byeong-Ok,"604,480",Action,Drama,Mystery,$0.71M,8.4,R
22,Avengers: Infinity War,Robert Downey Jr.,Chris Hemsworth,Mark Ruffalo,Chris Evans,"1,145,018",Action,Adventure,Sci-Fi,$678.82M,8.4,PG-13
23,Kaithi,Karthi,Narain,Arjun Das,George Maryan,"37,005",Action,Adventure,Crime,NaN,8.4,Not Rated
24,Asuran,Dhanush,Manju Warrier,Prakash Raj,Pasupathy,"31,663",Action,Drama,NaN,NaN,8.4,Not Rated
25,Top Gun: Maverick,Tom Cruise,Jennifer Connelly,Miles Teller,Val Kilmer,"619,582",Action,Drama,NaN,$718.73M,8.3,PG-13
26,Heat,Al Pacino,Robert De Niro,Val Kilmer,Jon Voight,"686,833",Action,Crime,Drama,$67.44M,8.3,R
27,North by Northwest,Cary Grant,Eva Marie Saint,James Mason,Jessie Royce Landis,"337,316",Action,Adventure,Mystery,$13.28M,8.3,Approved
28,Star Wars: Episode VI - Return of the Jedi,Mark Hamill,Harrison Ford,Carrie Fisher,Billy Dee Williams,"1,087,935",Action,Adventure,Fantasy,$309.13M,8.3,PG
29,Mononoke-hime,Yôji Matsuda,Yuriko Ishida,Yûko Tanaka,Billy Crudup,"412,506",Animation,Action,Adventure,$2.38M,8.3,PG-13
30,Dangal,Aamir Khan,Sakshi Tanwar,Fatima Sana Shaikh,Sanya Malhotra,"200,058",Action,Biography,Drama,$12.39M,8.3,Not Rated
31,Kantara,Rishab Shetty,Kishore Kumar G.,Achyuth Kumar,Sapthami Gowda,"97,289",Action,Adventure,Drama,NaN,8.3,Not Rated
32,Vikram,Kamal Haasan,Vijay Sethupathi,Fahadh Faasil,Narain,"65,185",Action,Crime,Thriller,NaN,8.3,UA
33,K.G.F: Chapter 2,Yash,Sanjay Dutt,Raveena Tandon,Srinidhi Shetty,"141,534",Action,Crime,Drama,$6.60M,8.3,Not Rated
34,Shershaah,Sidharth Malhotra,Kiara Advani,Shiv Panditt,Pranay Pachauri,"125,851",Action,Biography,Drama,NaN,8.3,TV-14
35,Ratsasan,Vishnu Vishal,Amala Paul,Radha Ravi,Sangili Murugan,"47,666",Action,Crime,Drama,NaN,8.3,Not Rated
36,Batman Begins,Christian Bale,Michael Caine,Ken Watanabe,Liam Neeson,"1,523,960",Action,Crime,Drama,$206.85M,8.2,PG-13
37,Spider-Man: No Way Home,Tom Holland,Zendaya,Benedict Cumberbatch,Jacob Batalon,"821,175",Action,Adventure,Fantasy,$804.75M,8.2,PG-13
38,Jurassic Park,Sam Neill,Laura Dern,Jeff Goldblum,Richard Attenborough,"1,027,406",Action,Adventure,Sci-Fi,$402.45M,8.2,PG-13
39,1917,Dean-Charles Chapman,George MacKay,Daniel Mays,Colin Firth,"634,995",Action,Drama,War,$159.23M,8.2,R
40,Indiana Jones and the Last Crusade,Harrison Ford,Sean Connery,Alison Doody,Denholm Elliott,"787,477",Action,Adventure,NaN,$197.17M,8.2,PG-13
41,Kill Bill: Vol. 1,Uma Thurman,David Carradine,Daryl Hannah,Michael Madsen,"1,152,058",Action,Crime,Thriller,$70.10M,8.2,R
42,V for Vendetta,Hugo Weaving,Natalie Portman,Rupert Graves,Stephen Rea,"1,149,274",Action,Drama,Sci-Fi,$70.51M,8.2,R
43,Die Hard,Bruce Willis,Alan Rickman,Bonnie Bedelia,Reginald VelJohnson,"908,755",Action,Thriller,NaN,$83.01M,8.2,R
44,Ran,Tatsuya Nakadai,Akira Terao,Jinpachi Nezu,Daisuke Ryû,"130,929",Action,Drama,War,$4.14M,8.2,R
45,Kimetsu no Yaiba: Mugen Ressha-Hen,Natsuki Hanae,Akari Kitô,Yoshitsugu Matsuoka,Hiro Shimono,"66,779",Animation,Action,Adventure,$47.70M,8.2,R
46,Gangs of Wasseypur,Manoj Bajpayee,Nawazuddin Siddiqui,Tigmanshu Dhulia,Richa Chadha,"100,143",Action,Comedy,Crime,NaN,8.2,Not Rated
47,Yôjinbô,Toshirô Mifune,Eijirô Tôno,Tatsuya Nakadai,Yôko Tsukasa,"127,195",Action,Drama,Thriller,NaN,8.2,Not Rated
48,K.G.F: Chapter 1,Yash,Srinidhi Shetty,Ramachandra Raju,Archana Jois,"92,940",Action,Crime,Drama,NaN,8.2,Not Rated
49,Baahubali 2: The Conclusion,Prabhas,Rana Daggubati,Anushka Shetty,Tamannaah Bhatia,"108,482",Action,Drama,NaN,$20.19M,8.2,Not Rated

In [63]:
df2.to_csv('second.csv')